version: '3'
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - "3310:3310"  # ClamAV daemon port
    environment:
      - CLAMD_SETTINGS_MAXQUEUE=200
      - CLAMD_SETTINGS_LOGTIME=1
    volumes:
      - clamav_db:/var/lib/clamav  # Persist virus definition database
    restart: unless-stopped

volumes:
  clamav_db:
