version: "1.0"
# networks:
#   default:
#     external:
#       name: ${NETWORK_NAME}

services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    image: redis:7.2.2
    expose:
      - 6379
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=1
    env_file:
      - .env
volumes:
  redis-data:
    driver: local
