openapi: 3.0.0
info:
  title: Onton Reward API
  description: API for rewarding users based on specific events. The event must be ongoing; otherwise, the reward cannot be created.
  version: 1.0.0
servers:
  - url: https://app.onton.live/api/v1
paths:
  /reward:
    post:
      summary: Reward a user
      description: Sends a reward to a user for a specific event. The event must be ongoing; otherwise, the reward cannot be created.
      operationId: rewardUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_uuid:
                  type: string
                  format: uuid
                  example: "fcda3846-3861-437e-8e4c-c75304d9ef29"
                  description: "Unique identifier for the event. The event must be ongoing."
                reward_user_id:
                  type: integer
                  example: 123456789
                  description: "User ID of the recipient."
      responses:
        '200':
          description: Reward successfully sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: object
                    properties:
                      reward_link:
                        type: string
                        example: "https://t.me/ton_society_bot/start?startapp=outmine-tournament-1-day-1&mode=compact"
        '400':
          description: Invalid request parameters or event not ongoing
        '401':
          description: Unauthorized request
        '500':
          description: Internal server error
      security:
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
